codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  status:
    project:
      default: false  
        informational: true

    patch:
      default:
        enabled: yes
        target: 80
