codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  status:
    project:
      default:  
        target: 80%    # the required coverage value
        threshold: 1% 
    patch:
      default:
        enabled: yes
        target: 80
