- name: Run Python script
  run: python script.py 
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REPO: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
    GITHUB_SHA: ${{ github.sha }}
    CODECOV_CONTEXT: 'codecov/project'
