name: Bypass Codecov Check

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]

jobs:
  bypass-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Check labels and set status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          CODECOV_CONTEXT: 'codecov/project'
        run: |
          import requests
          import os

          api_url = f"https://api.github.com/repos/{os.environ['REPO']}/pulls/{os.environ['PR_NUMBER']}/labels"
          headers = {"Authorization": f"token {os.environ['GITHUB_TOKEN']}"}
          response = requests.get(api_url, headers=headers)
          labels = [label['name'] for label in response.json()]

          if 'skip-codecov' in labels:
            status_url = f"https://api.github.com/repos/{os.environ['REPO']}/statuses/{os.environ['GITHUB_SHA']}"
            data = {
              "state": "success",
              "context": os.environ['CODECOV_CONTEXT'],
              "description": "Codecov check bypassed by label",
              "target_url": ""  # Optional: URL to more details
            }
            requests.post(status_url, headers=headers, json=data)
