jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install yq (Mike Farah's version)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod a+x /usr/local/bin/yq

      - name: Check yq version
        run: yq --version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate coverage report
        if: "!contains(github.event.pull_request.labels.*.name, 'Skip_Coverage_Check')"
        run: mvn test jacoco:report

      - name: Modify codecov.yml dynamically
        run: |
          yq eval '.coverage.status.project.maintest.target = "75%"' -i codecov.yml

      - name: Upload coverage reports to Codecov
        if: "!contains(github.event.pull_request.labels.*.name, 'Skip_Coverage_Check')"
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: maintest
          fail_ci_if_error: true

      - name: Upload fallback coverage report to Codecov
        if: "contains(github.event.pull_request.labels.*.name, 'Skip_Coverage_Check')"
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: skipcheck
