name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate coverage report
        run: mvn test jacoco:report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          #token: ${{ secrets.CODECOV_TOKEN }}
          # The path to the coverage report can be left as default if you're using JaCoCo's default output path.
          # file: ./target/site/jacoco/jacoco.xml
          # `slug` is optional and can be removed if your GitHub repository name matches the one on Codecov.
          # slug: asekawa
          fail_ci_if_error: true # Optional: Specify if the CI build should fail when Codecov fails.
